server:
    port: 8084

spring:
    profiles:
        active: dev

spark:
    host: dkarag.spark://host:port
    applicationName: application_Name
    parquetFolderPath: folder_path_where_tables_are_being_sqooped
    executorCores: num_of_cores_per_executor
    memoryPerExecutor: allocated_memory_per_executor #m for MByte, G for Gigabyte (1000m or 1g)
    sparkDriverMemory: allocated_memory_for_spark_driver #m for MByte, G for Gigabyte (1000m or 1g), default is 1000m
    coresPerSparkSession: num_of_cores_per_SparkSession #recommended

database:
    jdbc:
        username: root
        password:
        url: jdbc:mysql://:3306/dev_ab?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
